version: 1
disable_existing_loggers: False

formatters:
  json:
    format: >
      {
        "timestamp": "%(asctime)s",
        "type": "%(levelname)s",
        "msg body": {
          "id": "%(id)s",
          "content": "%(message)s"
        },
        "module": "%(module)s",
        "function": "%(funcName)s",
        "line": "%(lineno)d",
        "thread": "%(threadName)s",
        "process": "%(process)d",
        "execution_time": "%(execution_time)s",
        "user_id": "%(user_id)s",
        "correlation_id": "%(correlation_id)s"
      }

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: json
    stream: ext://sys.stdout

  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: json
    filename: logs/app_dev.log
    when: midnight
    backupCount: 7
    encoding: utf8
    delay: true  # Prevents unnecessary file creation
    utc: true     # Uses UTC timestamps for consistency

  cloudwatch:
    class: watchtower.CloudWatchLogHandler
    level: INFO
    formatter: json
    log_group: "dev-log-group"
    stream_name: "app-dev"
    region_name: "us-east-1"
    boto3_profile_name: null
    use_queues: true

loggers:
  app:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  aws:
    level: INFO
    handlers: [cloudwatch]
    propagate: no
